# Generated by Django 6.0.5 on 2026-05-26 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='analysisresult', name='interview_questions'),
        migrations.AddField(
            model_name='analysisresult',
            name='interview_questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list),
        ),
        migrations.RemoveField(model_name='analysisresult', name='missing_skills'),
        migrations.AddField(
            model_name='analysisresult',
            name='missing_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list),
        ),
        migrations.RemoveField(model_name='analysisresult', name='strengths'),
        migrations.AddField(
            model_name='analysisresult',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list),
        ),
        migrations.RemoveField(model_name='analysisresult', name='weaknesses'),
        migrations.AddField(
            model_name='analysisresult',
            name='weaknesses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list),
        ),
        migrations.RemoveField(model_name='resume', name='extracted_skills'),
        migrations.AddField(
            model_name='resume',
            name='extracted_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list),
        ),
    ]
